### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by panuchka** [NightCatSama/vue-slider-component#494]
#### Describe the feature

Vue 3 is now released, and we would like to see the slider updated to support Vue 3!

#### Describe the solution you'd like

Vue slider component supports Vue 3

**Comment by NightCatSama** [comment]
The next version with vue3 support has been released, but it's still in beta, if you find any bugs you can report back to me!

```bash
$ yarn add vue-slider-component@next
# npm install vue-slider-component@next --save
```

**Comment by potatoDie** [comment]
I'm trying the Basic Example. As soon as I start dragging I get the values 'v', 'a', 'l', 'u' and 'e'

**Comment by NightCatSama** [comment]
@potatoDie I forgot to specify, because `data` had a type conflict in vue3.x (vue-class-component@next), so it was temporarily changed to `vData`. I should change it back later, but for now, try not to set the `data` prop.

online example:
<https://jsfiddle.net/3ea4qbg9/1/>

**Comment by potatoDie** [comment]
@NightCatSama Thanks. I got it working too on CodeSandbox, but locally I'm working with Vite and the bug persists.

**Comment by NightCatSama** [comment]
@potatoDie Thanks for the feedback, v4.0.0-beta.2 has been fixed.

**Comment by potatoDie** [comment]
Perfect, thanks!

**Comment by terax6669** [comment]
I'm migrating a project to Vue 3, here's what I've noticed:

1. When using `:v-model` the value of the slider was not updated, had to use `:modelValue` +`@change` for that. I've noticed that you're using `@Prop` instead of `@Model` in https://github.com/NightCatSama/vue-slider-component/blob/20d3d3ac9a3202cad6f0f9a3d77d9b14d46553ca/lib/vue-slider.tsx#L65
2. During the migration parts of my component weren't working as intended yet. When passing `NaN` to `:min`, `:max` and `:value` I got a bunch of JS errors about accessing property x of undefined. At first I thought it was some internal error but it turned out to be my fault in the end. There could be a better way of handling it and giving the user a clearer error message.

```vue
<vue-slider
	:value="zoom"    <- NaN
	@change="handleZoomChangeThrottled"
	:contained="true"
	direction="btt"
	:dot-size="23"
	:width="9"
	:drag-on-click="true"
	height="200px"
	:interval="0.001"
	:max="maxZoom"    <- NaN
	:min="Math.floor(minZoom * 1000) / 1000"    <- NaN
	tooltipPlacement="right"
	:tooltip-formatter="zoomTooltipFormatter"
/>
```

**Comment by fgarit-te** [comment]
I am migrating my project to Vue 3. We are using the slider both with a single and 2 knobs. A lot of it is broken. I will try to come up with a sample project showcasing those problems, but is there a timeline for full support of Vue 3? I mean this version still throws a bunch of vue 3 compatible mode warning
![image](https://user-images.githubusercontent.com/46822958/143323534-ce1a4e5d-5080-4a1f-b202-7496d0a0aa1f.png)
